### ISSUE TITLE
Allow web-browsers to issue cross-domain requests

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/OPTiMaDe#101]
This only concerns JavaScript requests done from the web-browsers via **XMLHttpRequest** and **ActiveXObject**. By default the web-browsers are not allowed to fetch content from an OPTiMaDe server, living on an external domain, unless such header is included into the server's response:

`Access-Control-Allow-Origin: *`

May I kindly ask you to include this header into your server implementation responses.

**Comment by dwinston** [comment]
@blokhin please start a PR to add this as a SHOULD or so to the `optimade.md` spec?

**Comment by rartino** [comment]
Are there security concerns we should worry about with this? The only thing I immediately can see is on the client--- if you are not careful with how you render data fetched via OPTIMaDe, the owner of the database may pull off some cross-site-scripting. But that, to me, is on the client.

Otherwise, I think this is commonly restricted to block man-in-the-middle-type attacks, but I do not yet see how that applies here. I'll think a bit more on this. But I think SHOULD is the right level for it.

**Comment by sauliusg** [comment]
The cross-site scripting is not so much an issue here, AFIU, but setting `Access-Control-Allow-Origin: *` opens slight possibility for subverting database data. If the scenario described in [Quora](https://www.quora.com/What-is-same-origin-policy-Why-is-it-required-How-is-it-a-security-vulnerability?share=1)

**Comment by sauliusg** [comment]
I do not like the `Access-Control-Allow-Origin: *`, considering it a bad design and possible security thread for our servers. Also, it seems to be not necessary: already without the ACAO header, 

> the same-origin policy allows inter-origin HTTP requests with GET and POST methods

[W3C Same Origin Policy](https://www.w3.org/Security/wiki/Same_Origin_Policy), and `GET` is the only request currently relevant for OPTiMaDe.

I therefore suggest either not having any mention of `Access-Control-Allow-Origin` in the OPTiMaDe spec, or at least changing 'SHOULD' to 'MAY'.

**Comment by blokhin** [comment]
Please, see https://github.com/Materials-Consortia/OPTiMaDe/pull/105#issuecomment-502489546
