### ISSUE TITLE
Add license to specification

### ISSUE THREAD

**Issue by ltalirz** [Materials-Consortia/OPTiMaDe#111]
as discussed I plan to add the Creative Commons 4.0 BY license,
potentially with separate suggestions pointing out that optimade.org is the official optimade organisation and that name clashes should be avoided.

I'll also try to give a look to what other specification bodies do for such cases.

**Comment by merkys** [comment]
I vote for CC-BY or a bit stricter [CC-BY-SA](https://creativecommons.org/licenses/by-sa/3.0/), which requires the derivatives to be licensed under the same license.

**Comment by davidwaroquiers** [comment]
I would keep it CC-BY and not CC-BY-SA as this may prevent some commercial databases to be willing to use the API.

**Comment by merkys** [comment]
> I would keep it CC-BY and not CC-BY-SA as this may prevent some commercial databases to be willing to use the API.

I don't see why. Both JSON and YAML specifications explicitly forbid any modifications, yet everyone uses them.

**Comment by merkys** [comment]
I was about to prepare a PR with CC-BY-SA license, but made up my mind before clicking "Submit": the choice of the license is quite an important decision, and it clearly needs more than two approvals. I'd like to hear more opinions here.

**Comment by rartino** [comment]
Indeed--- so do you feel strongly that this is a release blocker for v0.10? (as opposed to v1.0?) I'm not sure not having a license for the specification document is a critical problem, it just means no one is allowed to reuse/republish it until we have sorted out which license to use.

But, all that said, CC-BY-SA seems good to me.

**Comment by merkys** [comment]
> I'm not sure not having a license for the specification document is a critical problem, it just means no one is allowed to reuse/republish it until we have sorted out which license to use.

Agree. I am usually disappointed by software not having clear license statements as it renders such software mostly unusable outside the sandbox, but for documentation this is not an obstacle. Removed "blocking-release" tag.

**Comment by CasperWA** [comment]
@csadorf and I are working on the MarketPlace project (an H2020 project designed to create a web platform for materials science). We are considering using OPTiMaDe internally, but would need to modify some of the specs for our needs, etc. This is fine with the CC licence.

However, we would _need_ clarification on which licence OPTiMaDe will be using.

If it will be CC-BY-SA, would it be enough for us to publish our "final" modified spec under the CC-BY-SA licence and then _also_ licence the spec "in use" under a different licence (since this will be needed for all of MarketPlace's internal code)?

It seems to me this would never be an issue if CC-BY is chosen, correct?

**Comment by merkys** [comment]
> If it will be CC-BY-SA, would it be enough for us to publish our "final" modified spec under the CC-BY-SA licence and then _also_ licence the spec "in use" under a different licence (since this will be needed for all of MarketPlace's internal code)?
> 
> It seems to me this would never be an issue if CC-BY is chosen, correct?

CC-BY is also a good option. We may also investigate alternative documentation licenses.

**Comment by rartino** [comment]
I suspect you cannot relicense a CC-BY-SA document under another license. Because if that license does not mandate modifications to be CC-BY-SA-licensed, that version could diverge into a "closed" version of the original where edits are not given back.

Are you allowed to share any info on what needs to be changed for MarketPlace? Would it be possible to instead get your needs covered by the real OPTiMaDe, instead of creating a fork?

**Comment by csadorf** [comment]
The main issue with CC-BY-SA (as opposed to CC-BY) in this context is that it would make it impossible for us to ever fork the OPTiMaDe API and redistribute it under a different license, forever binding us to the development and decision speed of the Materials-Consortia organization. That creates a significant risk for us and I'm not sure that we can reasonably recommend adopting the OPTiMaDe API as the primary API of our services if that licensing model was adopted.

That said, without any license we can **definitely** not use it, so a decision on this should be made rather sooner than later.

>  Would it be possible to instead get your needs covered by the real OPTiMaDe, instead of creating a fork?

@rartino I think it is in everybody's interest that the API is not forked and that all changes are contributed back to OPTiMaDe. However, we need to be able to make independent decisions for our own endpoint and that might mean that we might need to diverge a little bit at least temporarily. I don't think that's completely impossible with CC-BY-SA, but it certainly seems more complicated.

**Comment by merkys** [comment]
> That said, without any license we can **definitely** not use it, so a decision on this should be made rather sooner than later.

This is a strong argument in favor of making this OPTiMaDe issue a release blocker.

I am now more convinced about the advantage of CC-BY over CC-BY-SA.

**Comment by rartino** [comment]
My question was meant more on the technical side than the license argument side: is there anything you already see that will need to be modified in OPTiMaDe to fit your use? I'm asking because I've heavily been pushing for the implementation-extensible design we have now from the start, exactly to avoid anyone having to be "bound to the development and decision speed of the Materials-Consortia organization".

Returning to the license discussion, I don't quite see the MarketPlace use as an argument against CC-BY-SA. That license very explicitly allows the creation of derivative works, but they have to be licensed CC-BY-SA so that we in OPTiMaDe can re-integrate text changes upstream. The only argument for needing CC-BY seems to be "we need to license everything with our own license". But, I'm fairly sure that policy can only apply to code in your project, not protocol specification documents. Otherwise, will the MarketPlace avoid the use of any internet protocols, including http, that are standardized in RFCs with far more restrictive licenses than CC-BY-SA?, i.e., they typically [do not grant the right to create derivative works at all](https://trustee.ietf.org/reproduction-rfcs-faq.html)...

All that said, there are other good arguments for CC-BY over CC-BY-SA. If we ever want to turn (part of) OPTiMaDe into a more official internet standard, it turns out it may be useful for us to be able to re-license it under a stricter license without having to ask everyone who've contributed.

**Comment by csadorf** [comment]
> My question was meant more on the technical side than the license argument side: is there anything you already see that will need to be modified in OPTiMaDe to fit your use? I'm asking because I've heavily been pushing for the implementation-extensible design we have now from the start, exactly to avoid anyone having to be "bound to the development and decision speed of the Materials-Consortia organization".
>

I can't fully anticipate the possibly needed changes at the moment, however I recognize and appreciate this flexibility of the standard and I think that it provides a reasonable path to introduce any needed deviations. That said, I believe we need to clearly distinguish between the standard being permissive to changes and the permissiveness of the standard document. The former relates to how we can modify the standard without violating its stipulations, while the latter is related to whether we can actually implement such changes to the original specification document and under what conditions we can publish them.

> Returning to the license discussion, I don't quite see the MarketPlace use as an argument against CC-BY-SA. That license very explicitly allows the creation of derivative works, but they have to be licensed CC-BY-SA so that we in OPTiMaDe can re-integrate text changes upstream.

I believe it is also in the interest of the Materials-Consortia that there are no disproportionate barriers to the use of the standard.

> The only argument for needing CC-BY seems to be "we need to license everything with our own license". But, I'm fairly sure that policy can only apply to code in your project, not protocol specification documents.

Yes, and again, I did not say that it would be completely impossible, however in that case we would need to ensure that any work related to the API is treated differently from the rest of the code base, which creates additional maintenance burden and - more importantly - might conflict with requirements by our funding agencies and industry partners. I don't think that it is impossible to manage, it just makes things more complicated.

> Otherwise, will the MarketPlace avoid the use of any internet protocols, including http, that are standardized in RFCs with far more restrictive licenses than CC-BY-SA?, i.e., they typically [do not grant the right to create derivative works at all](https://trustee.ietf.org/reproduction-rfcs-faq.html)...

I am not sure whether I misunderstand you argument, but I do not see any likely scenario where we would need to modify the `http` protocol standard and publish these modifications. But yes, if there was a need to extend any of the standards published by the RFC or a different standard body, we would need to weight the cost of abiding to all applicable rules and regulations related to that against some alternative way of achieving the same goal. 

> All that said, there are other good arguments for CC-BY over CC-BY-SA. If we ever want to turn (part of) OPTiMaDe into a more official internet standard, it turns out it may be useful for us to be able to re-license it under a stricter license without having to ask everyone who've contributed.

I agree, there are good arguments for either license variant. I am making myself heard here to ensure that the collaborators of the Materials-Consortia are aware that a copy-left license might pose a barrier for some organizations to adopt the standard as a basis for the development of their services.

**Comment by ltalirz** [comment]
What I had in mind when I opened the issue was for people not to have to worry when they e.g. want to copy snippets of the specification for documenting their API.
Simon mentioned another use case, which is a derivative standard extending the spec.

Looking at the practises of the IETF, perhaps in reality the first case is not actually an issue and would fall under "fair use", at least in the US.
As for the second case, I think it is up to us to decide whether we want a derivative standard to be published under the same license.
I don't really have a strong opinion on this.

I do think it is another story when it comes to supporting *code* that people might want to incorporate into their implementations - this is another reason why I think it would be better not to 
 include code in the same git repository as the specification (note that e.g. the optimade-python-tools are MIT licensed).
In any case, we can make clear that the license decided here applies to the optimade specification only.

**Comment by csadorf** [comment]
> Looking at the practises of the IETF, perhaps in reality the first case is not actually an issue and would fall under "fair use", at least in the US.

Yes, *using* the API, that means offering this API as an interface to our services, would indeed be covered by fair use both in the US and the EU to my understanding. However, we would need to be very careful to not plagiarize any of the language of the specification if we wanted to describe that interface as part of our own published documentation. All of my comments on this issue are strictly related to the standard *document*, nothing else.

**Comment by csadorf** [comment]
Are there any updates concerning the licensing issue?

**Comment by mkhorton** [comment]
Agreed it is important to reach a decision here. Materials Project recently adopted CC-BY 4.0, we would be behind using CC-BY unless there was a convincing argument otherwise. The "SA" term is good in theory, but in terms of encouraging adoption (the most important aspect of a standard) I think the less restrictive terms are better for the reasons discussed in this thread.
