### ISSUE TITLE
conflicting definitions of content of "entries"

### ISSUE THREAD

**Issue by ltalirz** [Materials-Consortia/OPTiMaDe#12]
There are currently two, conflicting definitions of the basic content of an "entry"
 * [Section 4.1.2](https://github.com/Materials-Consortia/OPTiMaDe/blob/v0.9.5/optimade.md#412-json-api-response-schema) describing the case of multiple entries
 * [Section 6.1](https://github.com/Materials-Consortia/OPTiMaDe/blob/v0.9.5/optimade.md#61-properties-used-by-multiple-entry-types) describing properties used by multiple entry types

First of all, having two definitions seems unnecessary, since [4.2.2](https://github.com/Materials-Consortia/OPTiMaDe/blob/v0.9.5/optimade.md#422-response-schema) states: 
> The response for a 'single entry' endpoint is the same as for 'entry listing' endpoint responses, except that the value of the "data" key MUST have only one entry.

Second, one needs to decide for one of the two, in particular
 * `local_id` vs `id`
 * ~~`last_modified` vs `modification_date`~~
 * `immutable_id` vs nothing

I'm not sure whether this decision has already been made at some point and just hasn't found its way into the spec yet, could someone please comment on that?

~~Let me just reiterate that `modification_date` is a standard field in JSON schema as already pointed out in #1~~
**Edit**: Issue #1 has been fixed in PR #77, keeping only `last_modified`.

**Comment by rartino** [comment]
I'm sure the writing/organization of things can be improved and clarified, but I don't see a bug other than that `last_modified` in Sec 4.1.2 should be the jsonapi mandated `modification_date` as was reported in #1. 

Note that Section 6.1.1 doesn't say that the fields it lists are the ones (and the only ones) that should appear in any specific output. 6.1.1 is really just intended mostly as an 'appendix' that lists field names and gives more precise details on how they are defined, wherever they appear in the output. The requirements for what MUST and MAY be included in a response is meant to be in section 4. So, if you are wondering if you should be reading section 4 or 6 to know which fields needs to be in some specific output, the answer is section 4.

The three ID fields were an intentional result from the 2016 workshop, with the following intent:
- `id` is the jsonapi mandated id that sits at top level. This is an id that OPTIMaDe puts some requirements on in 6.1.1. Hence, it is possible that for some databases this cannot be their own preferred id.
- `local_id`, on the other hand, has no requirements whatsoever. Here databases get to communicate their own ids for each record. 
- `immutable_id` should be used if the database preferred id points to something that may change. Some databases like to use a preferred id to point to "the latest version" of a record, but do still keep around older versions. In such cases, `immutable_id` MAY be provided to give information about what id can be used to find the precise version that was returned, in case this record changes in the future.

**Comment by dwinston** [comment]
Where is `modification_date` mandated in [https://jsonapi.org/format/1.0/](https://jsonapi.org/format/1.0/) ? I would like a field in "attributes" mandated for all entry responses, either `last_modified` or `modification_date`.

**Comment by merkys** [comment]
> Where is `modification_date` mandated in https://jsonapi.org/format/1.0/ ? I would like a field in "attributes" mandated for all entry responses, either `last_modified` or `modification_date`.

`modification_date` is defined not in JSON API, but in OPTiMaDe's JSON API. I agree this is quite confusing.

**Comment by merkys** [comment]
> * `immutable_id` vs nothing

@ltalirz I feel that `immutable_id` must stay in the spec as an optional field. It's use is comparable to a permalink. Providers who can't serve it can just skip the field.

**Comment by ltalirz** [comment]
I see. I now realize that when originally opening the issue, part of what I thought needed changing came from a misunderstanding of the headline "Properties used by multiple entry types" of section 6.1.

I may have confused "properties" ([which in JSON simply means key-value pair](https://json-schema.org/understanding-json-schema/reference/object.html)) with "attributes" (which for entries e.g. do *not* contain an `id` field etc.).

In my defense, I would like to point out that we have a definition of the term "property" [in the spec](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md#h.2) but it says

> Property: Anything that can be in the filtering of results.

which differs a bit from the JSON definition linked above.

Two points:
 1. If we agree that the intention in section 6.1 was to mean "properties = key-value pairs", then I think we can consider this issue resolved.
 2. It might be worth clarifying the meaning of "property" vs the JSON definition in the spec and then, potentially, adapt the wording of 6.1 to make things clear.

**Comment by CasperWA** [comment]
> Two points:
> 
> 1. If we agree that the intention in section 6.1 was to mean "properties = key-value pairs", then I think we can consider this issue resolved.

In a discussion between @rartino, @giovannipizzi, @merkys, and myself, we found/agreed that it is not just attributes that are properties, but also, e.g., `type` and `id`. The fact they they are output at the same level as `attributes` is _only_ to show that they are special properties and MUST always be present for a resource object.

> 2. It might be worth clarifying the meaning of "property" vs the JSON definition in the spec and then, potentially, adapt the wording of 6.1 to make things clear.

An issue has been opened for this; #109.

**Comment by ltalirz** [comment]
@CasperWA The link seems correct - here is the quote

> Objects are the mapping type in JSON. They map “keys” to “values”. In JSON, the “keys” must always be strings. Each of these pairs is conventionally referred to as a “property”.

**Comment by CasperWA** [comment]
I cannot find this in the actual spec anywhere, but this is fine.
If we simply restrict a `property` to be a set of key-value-pairs _only_ under the top-level `data` field, then all is good and fine, I think. It would make `type`, `id`, `attributes` and all fields under `attributes` (including their respective values) properties, effectively. Which is fine, I think. However, I will refer to issue #109 for further discussion of this.

**Comment by ltalirz** [comment]
The definition of "property" in PR #126 is consistent with point 1 in my [comment](https://github.com/Materials-Consortia/OPTiMaDe/issues/12#issuecomment-501870044).
So, this issue can be closed.
