### ISSUE TITLE
Extend response_fields to support field exclusion

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTiMaDe#181]
Currently `response_fields` query parameter allows the user to explicitly enumerate fields to be included in the response. I suggest a mechanism to explicitly exclude particular field(s) using the same `response_fields` query parameter.

Now `response_fields=a,b,c` means that the user requests response with only `a`, `b` and `c` fields. As field names cannot have `-` sign, `response_fields=-a` could be defined to stand for *all fields excluding `a`*, and `response_fields=-a,b,c` - *all fields excluding `a`, `b` and `c`* etc.

An alternative proposition is to introduce `response_fields_exclude` query parameter. However, such introduction would also require description of how `response_fields` and `response_fields_exclude` interact.

**Comment by rartino** [comment]
Can you give a scenario where this would be useful? 

My thought process is that this feature would just cater to bad habits. Sure, we all like to write less (give me `-c` instead of `a,b,d,e`). But, if you are trying to save bandwidth (and what other reasons would you have to use `response_fields`?) and you start saying "everything except c" you are going to get, e.g., database-specific fields, or fields from newer version of the standard that you are anyway going to throw away. 

Regarding `response_fields_exclude`, well, also in your proposal you need to describe how multiple (+) and - entries interact. Is it an error for the same property to appear more than once? Or does the last (or first) take precedence?

**Comment by merkys** [comment]
> Can you give a scenario where this would be useful?
> 
> My thought process is that this feature would just cater to bad habits. Sure, we all like to write less (give me `-c` instead of `a,b,d,e`). But, if you are trying to save bandwidth (and what other reasons would you have to use `response_fields`?) and you start saying "everything except c" you are going to get, e.g., database-specific fields, or fields from newer version of the standard that you are anyway going to throw away.

The reason I came up with this proposal is usually huge amounts of data returned in `cartesian_site_positions`. In cases when I am sure I won't need the coordinates, it is convenient to ask for everything except that. 

> Regarding `response_fields_exclude`, well, also in your proposal you need to describe how multiple (+) and - entries interact. Is it an error for the same property to appear more than once? Or does the last (or first) take precedence?

The alternative proposition of `response_fields_exclude` should serve only as a motivation for my primary proposal. That is, it just showcases the problems arising when using yet another query parameter instead of `response_fields`.

**Comment by merkys** [comment]
This issue should be offset by solving #184
