### ISSUE TITLE
Species and species_in_sites

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTiMaDe#188]
Going back over the issues and PRs I have found that the `species` attribute for structure objects have been updated: #127.
This is fine, the sentiment of not using relevant data as dictionary keys makes complete sense.

However, as @fawzi also pointed out [in the same PR](https://github.com/Materials-Consortia/OPTiMaDe/pull/127#pullrequestreview-250247721), this will result in rather long `species` lists compared to previous versions.

In order to accommodate this, while also not having dictionary keys be data, I have a suggested change to `species_at_sites`, which should also reduce `species`:

Instead of having each data/species in `species_at_sites` be unique, let's not :)
This may be implemented in two ways, depending on the _need_ to have these pieces of data be unique:

1. **(No need for uniqueness)**: Simply have `species_at_sites` be a list of equal length to the first dimension of `cartesian_site_positions`, i.e., be equal to `nsites`. Make it a requirement that each string/piece of data in `species_of_sites` must match up with its corresponding site in `cartesian_site_positions`. Then lose the uniqueness of each string/piece of data in `species_of_sites`, but keep the requirement that for each unique data in `species_of_sites`, there must be a dictionary in the `species` list with its `name` value equal to it.

Example:
```json
{
  "nsites": 9,
  "species_at_sites": ["T1", "T1", "T2", "O1", "O1", "O1", "O1", "O2", "O2"],
  "species": [
    {"name": "T1", "chemical_symbols": ["Si"], "concentration": [1.0]},
    {"name": "T2", "chemical_symbols": ["Si", "Al"], "concentration": [0.8, 0.2]},
    {"name": "O1", "chemical_symbols": ["O"], "concentration": [1.0]},
    {"name": "O2", "chemical_symbols": ["O", "vacancy"], "concentration": [0.9, 0.1]}
  ]
}
```

2. **(Need for uniqueness)**: Do the same as for non-uniqueness, but let each piece of data in `species_at_sites` be a list of exactly length 2, where the first entry is the unique `species_at_sites` name, and the second is a unique `species` `name` value.

Example:
```json
{
  "nsites": 9,
  "species_at_sites": [
    ["T1", "T1"],
    ["T2", "T1"],
    ["T3", "T2"],
    ["O1", "O1"],
    ["O2", "O1"],
    ["O3", "O1"],
    ["O4", "O1"],
    ["O5", "O2"],
    ["O6", "O2"]
  ],
  "species": [
    {"name": "T1", "chemical_symbols": ["Si"], "concentration": [1.0]},
    {"name": "T2", "chemical_symbols": ["Si", "Al"], "concentration": [0.8, 0.2]},
    {"name": "O1", "chemical_symbols": ["O"], "concentration": [1.0]},
    {"name": "O2", "chemical_symbols": ["O", "vacancy"], "concentration": [0.9, 0.1]}
  ]
}
```

In this way we do not end up with `species` being a list of length `nsites`, but of the same length it "used to be", while at the same time, there are no dictionary keys containing data.

**Comment by CasperWA** [comment]
For clarification, the issue in the spec is the combination of the following requirements for `species_at_sites`:

- Each species MUST have a unique name.
- Each species name mentioned in the species_at_sites list MUST be described in the list property species (i.e. for each value in the species_at_sites list there MUST exist exactly one dictionary in the species list with the name attribute equal to the corresponding species_at_sites value).
- Each site MUST be associated only to a single species.

And for a `species`' name:

- REQUIRED; gives the name of the species; the name value MUST be unique in the species list;

Together with the fact that the length of `species_at_sites` MUST equal the length of the first dimension of `cartesian_site_positions`, this will make the `nsites` = length(`cartesian_site_positions`) = length(`species_at_sites`) = length(`species`)
And I find the latter equal sign superfluous, since it negates the original idea of having species.

If this is not the intent of the spec, then it should be clarified, otherwise I think it should be discussed.

**Comment by sauliusg** [comment]
> Together with the fact that the length of `species_at_sites` MUST equal the length of the first dimension of `cartesian_site_positions`, this will make the `nsites` = length(`cartesian_site_positions`) = length(`species_at_sites`) = length(`species`)
> And I find the latter equal sign superfluous, since it negates the original idea of having species.
> 
> If this is not the intent of the spec, then it should be clarified, otherwise I think it should be discussed.

My understanding is that the current spec does *not* require the last equal sign. The 'Each species MUST have a unique name' refers, in my understanding, to the requirement that each species in the species dictionary has unique name ('the name value MUST be unique in the species list' in the section [6.2.13 "species"](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#id65)). Indeed, it would be prohibitive to repeat the *same* species under a different name, just to make all species name in the 'species_at_site' list look different! Thus, in my understanding, the current spec mandates exactly what @CasperWA proposes as the option no. 1, which I support.
I suspect that it is the mention the 'Each species MUST have a unique name' in the section [6.2.12   "species_at_sites"](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#id64) that causes confusion. If this is so I suggest simply removing this sentence from the section [species_at_sites](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#id64), since it is already mandated in [species](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#id65) section.
