### ISSUE TITLE
Running the test environment in Docker

### ISSUE THREAD

**Issue by fekad** [Materials-Consortia/OPTiMaDe#192]
The `Dockerfile` below can be used to run the test on macOS or other operating systems. This could be useful for Linux users as well because trusty is not the latest distribution...

`cat Dockerfile`
```
FROM ubuntu:trusty

RUN apt-get update \
 && apt-get install -y -q --no-install-recommends \
        locales \
        ant \
        unzip \
        wget \
        make \
        default-jdk \
        subversion \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

ENV LANG en_US.utf8

WORKDIR /root/optimade
COPY . .

CMD ["/bin/bash", "-c", "make clean; make tools; make grammars; make tests; make listdiff"]
```

Usage:
- Building the image locally:
  `docker build -t optimade .`
- Running the tests:
  `docker run -it --rm optimade:latest`
- Running the test by using the local filesystem:
  `docker run -it --rm -v $PWD/:/root/optimade optimade:latest`

Note: It is important that the repository should be "clean" because `make clean` keeps some of the files of the tools in place. (a dirty way: `rm -rf tests; git restore tests`)

**Comment by rartino** [comment]
Thanks for the work with this. I've always found it a bit bothersome to run the tests, since they pull in external software which may not be safe and thus I have to run them in a VM. This docker setup looks safer.

I'd be happy to see this docker setup added to the test part of the repository. Perhaps we should even rework the test setup to run it in docker by default? (I.e., `make tests`). Pinging @sauliusg for his thoughts.
