### ISSUE TITLE
Refining the grammar of the `LengthComparison`

### ISSUE THREAD

**Issue by fekad** [Materials-Consortia/OPTiMaDe#199]
The "`LengthComparison`" rule has been defined as a "numeric comparison" in the ["Comparisons of list properties"](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#524comparisons-of-list-properties). On the other hand according to the [grammar](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#72the-filter-language-ebnf-grammar) the `Value` can be `String` or `Number` or `Property` where `String` doesn't make any sense. Also, in line with previous rules `Operator` could be optional with using `=` as a default. `Property` may be allowed to use.
Original definiton:
```
LengthComparison = LENGTH, Property, Operator, Value ;
```
Proposed definition:
```
LengthComparison = LENGTH, Property, [ Operator ], ( Number | Property ) ;
```

**Comment by rartino** [comment]
Note: to make `Operator` optional needs a text change in the specification. 

From a language design perspective, I'm not overly convinced about the syntax
```
  LENGTH list 3
```
Because this takes a less human-readable form and a more machine-readable prefix notation form than the filter language has used so far. So far, the LENGTH predicate can be thought of as something that "returns" a value, which then requires an operator for comparison. With that view, it is conceptually different from operators like `HAS`, e.g., `list HAS 3`. My opinion is that if we want to provide an "equal sign"-less length operator in line with the filter language so far, it should rather be on the form `list LENGTH 3`. 

As for `( Number | Property)` vs. `Value`, I recall @sauliusg having arguments for generally avoiding type-checking on the grammar/parser level, but I don't exactly recall them(?) In fact---I thought we had removed the type-restriction of Strings for the fuzzy string comparisons in a recent PR, but I see now that it still is there. (So if his arguments are convincing, we may also consider replacing `StringProperty` with `Value` in the `FuzzyStringOpRhs` rule for consistency.)

**Comment by sauliusg** [comment]
> From a language design perspective, I'm not overly convinced about the syntax
> 
> ```
>   LENGTH list 3
> ```

Here I agree with @rartino , I would leave the `Operator` as mandatory.

Not only this is more readable, it is more consistent with the overall grammar (we always have a comparison operator as infix, don't we?), and, in addition, by dropping the operator I think we risk making the grammar ambiguous in the future.

**Comment by sauliusg** [comment]
> s for `( Number | Property)` vs. `Value`, I recall @sauliusg having arguments for generally avoiding type-checking on the grammar/parser level, but I don't exactly recall them

My argument would be that by making syntax more inclusive, we can express (encode) things in the language that are not used right now but might have sense in the future. Comparing a property with another property is a standard database/programming language construct, so I strongly anticipate it will come up necessary.

If our grammar permits such expressions, than we can make a backwards-compatible extension in the implementation by just implementing this functionality (which was previously diagnosed as unsupported), and amend the semantics part of the OPTiMaDe spec.

If we rule out some construct in the grammar, we will have to do all the above but in addition we will have to make changes in the grammar. Moreover, some other changes might come into conflict with this grammar rule, making it much more headache. 

Thus, I would argument for making grammar as much orthogonal and universal as possible.

**Comment by sauliusg** [comment]
> My opinion is that if we want to provide an "equal sign"-less length operator in line with the filter language so far, it should rather be on the form `list LENGTH 3`.

I agree.

**Comment by fekad** [comment]
> > s for `( Number | Property)` vs. `Value`, I recall @sauliusg having arguments for generally avoiding type-checking on the grammar/parser level, but I don't exactly recall them
> 
> My argument would be that by making syntax more inclusive, we can express (encode) things in the language that are not used right now but might have sense in the future. Comparing a property with another property is a standard database/programming language construct, so I strongly anticipate it will come up necessary.
> 
> If our grammar permits such expressions, than we can make a backwards-compatible extension in the implementation by just implementing this functionality (which was previously diagnosed as unsupported), and amend the semantics part of the OPTiMaDe spec.
> 
> If we rule out some construct in the grammar, we will have to do all the above but in addition we will have to make changes in the grammar. Moreover, some other changes might come into conflict with this grammar rule, making it much more headache.
> 
> Thus, I would argument for making grammar as much orthogonal and universal as possible.

In general, a completely agree with you, but here I was just thinking that comparing the length of a list with a string doesn't make any sense. Especially, the specification also mentions that it should be a numerical compersion.

**Comment by fekad** [comment]
> > My opinion is that if we want to provide an "equal sign"-less length operator in line with the filter language so far, it should rather be on the form `list LENGTH 3`.
> 
> I agree.

I think it is more readable and match very well to the [use](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#comparisons-of-list-properties) of `HAS`:
```
LengthComparison = Property, LENGTH, [ Operator ], ( Number | Property ) ;
```
Although there is an ongoing PR (#191), I'm happy to create a new one for this later if you think it worth it. (Of course, we can use `Value` and `PredicateComparison` if those are prefered)

**Comment by rartino** [comment]
As I said upthread, I'm not opposed to switching over to the syntax
```
list LENGTH 3
```
It arguably simplifies the language since this would completely remove predicates from it, for now.

But it cannot be with a statement quite on the form suggested by @fekad, because for the grammar to stay LL-parseable with this change the rule must fall into the `PropertyFirstComparison` category:
```
...

PropertyFirstComparison = Property, (
                ValueOpRhs |
                KnownOpRhs |
                FuzzyStringOpRhs |
                SetOpRhs |
                SetZipOpRhs |
                LengthOpRhs );
(* Note: support for SetZipOpRhs in Comparison is OPTIONAL *)

LengthOpRhs = LENGTH, [ Operator ], Value ;

...
```
And the production rules for `PredicateComparison`, `LengthComparison` are to be removed. 

Note that I put `Value` rather than `( Number | Property )` in the last RHS as I agree with @sauliusg point about types. I prefer not throwing a grammar parser error for `list LENGTH "3"`, but rather handle it further down in my code as a normal type error, which also allows a future extension where "3" in this situation is interpreted as 3.

If we all can agree on that point, I'd suggest simultaneously slipping in this change:
```
FuzzyStringOpRhs = CONTAINS, Value |
               STARTS, [ WITH ], Value |
               ENDS, [ WITH ], Value ;
```
and delete the production rule for `StringProperty`.

**Comment by fekad** [comment]
Closing this issue because there is a PR (#221) which implements these suggestions

**Comment by CasperWA** [comment]
Since #221 has not been merged yet, I will keep it open, letting the PR close it auto-magically :)
