### ISSUE TITLE
Requirement level of properties described in "6. Entry list" is not specified

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTiMaDe#2]
[6. Entry list](https://github.com/Materials-Consortia/OPTiMaDe/blob/v0.9.5/optimade.md#6-entry-list) defines entry properties, however, it is not specified which of these properties MUST be present and which are OPTIONAL. I suggest noting the requirements explicitly.

**Comment by rartino** [comment]
I agree that this should be specified somewhere, but I don't think the right place is under [6. Entry list](https://github.com/Materials-Consortia/OPTiMaDe/blob/v0.9.5/optimade.md#6-entry-list) because that really just is a list of definitions of what these properties are, in any context. So I rather think the place is in [4.1.2 JSON API](https://github.com/Materials-Consortia/OPTiMaDe/blob/master/optimade.md#412-json-api-response-schema) response schema; where under attributes it says "containing key-value pairs representing the entries properties". Hence, the fix for this connects to #3 in that both things could be clarified in the same place.

But then is the question: should any of these entry properties be mandatory?

**Comment by merkys** [comment]
> So I rather think the place is in [4.1.2 JSON API](https://github.com/Materials-Consortia/OPTiMaDe/blob/master/optimade.md#412-json-api-response-schema) response schema

I agree.

> But then is the question: should any of these entry properties be mandatory?

Strictly speaking all properties can be made optional in case the ``id`` is used to store database-specific identifiers (doesn't this supersede the need for ``local_id`` property?). I can think of databases not having values for ``last_modified`` nor ``immutable_id``.

**Comment by CasperWA** [comment]
This has partly been implemented in section [6.2. Structure Entries](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md#62-structure-entries) for a "structure".

Since section [4.1.2. JSON API Response Schema](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md#412-json-api-response-schema) only specifies the general schema of the response (and the same is true for section [4.2.2. Response Schema](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md#422-response-schema)) and we would want to add other entry types ("calculation", "md_structure", ...), it makes sense to create an overview table under each entry in section [6. Entry List](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.md#6-entry-list) that summarizes what is mandatory and what is optional for each entry type.

**Comment by ltalirz** [comment]
To summarize the status quo: There is currently no clear rule for what should go into section 4 and what should go into section 6 of the spec. 

For example, in #12, @rartino wrote
>  6.1.1 is really just intended mostly as an 'appendix' that lists field names and gives more precise details on how they are defined, wherever they appear in the output. The requirements for what MUST and MAY be included in a response is meant to be in section 4.

However, this is clearly no longer the case, as section 6.2 now specifies what MUST and MAY be included in structure responses for example.

I personally find the "appendix approach" anyhow suboptimal because it means there are potentially two places where I need to look as an implementer of a given response (either the information in the appendix is relevant, and then I need to look there, or it is not, and then it does not need to be in the spec). This leaves the question of *how* to subdivide the spec.

Here is a proposal:
 * Anything that is used by multiple entry listing endpoints goes into section 4.1
   (this concerns the sections that are now 6.1 and 6.6)
 * Anything that concerns a specific entry listing endpoint remains in section 6.
 * Where applicable, descriptions should always specify which properties are required and optional.

Do you agree?

P.S. While going through the spec I noticed that there is a possibility of confusion arising from the use of the term "JSON API Response Schema" e.g. as the title of sections 4.1.2/4.2.2. Without context, one would expect these sections to be concerned only with JSON API definitions, while they actually refer to the schema relevant to the default `response_format`.
I've opened PR #137 to add the meaning of the term to the definitions.

**Comment by rartino** [comment]
I'll clarify my present position on what goes in Sec 4 vs Sec 6.

For the purpose of organization, I like to view Sec 1-5 as the definition of a, in a sense, fully generic database query API. I.e., Sec 1-5 shouldn't contain anything that is materials data-specific (it is fine in examples, but not as part of the specification). Then, I like Sec 6 to provide the full definition of all the identifiers we need to provide materials data using this database query API.

I believe this is achieved in PR #150. Along with the already merged #137 that I think fully addressed the "P.S" in @ltalirz comment above, I have marked that PR to close this issue. If anyone disagrees, please edit out the corresponding 'closes' in that PR.
