### ISSUE TITLE
Add formatting checks, e.g., remove whitespace

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTIMADE#239]
In consideration of #235 and other previous similar PRs, it would be good to have formatting checks, i.e., checking for trailing whitespace and more.

This may either be implemented as a pre-commit check that one would need to install locally or as a Travis check (or both).

**Comment by rartino** [comment]
This should be easy to do, given the makefile changes that were merged in #195. It could just be added to the audit target, the same way the AUTHORs sorting is audited since that PR. But do we actually want to travis-check reject spurious whitespace? It seems it could be a hassle.

On the other hand, maybe people should simply adopt a workflow to `make audit` or `make docker_audit` before submitting a PR (maybe we should add that to our docs.)

**Comment by CasperWA** [comment]
It would be nice to not have to do these "remove whitespace" (and similar) PRs intermittently in the future in any case.

Personally, I like the pre-commit option, where any whitespace is automagically removed when committing, and then you stage the changed files and commit again.
It couldn't be done with the markdown file previously, but should be fine for the rst.
