### ISSUE TITLE
Optimade CORS-bypassing server for the web-browsers

### ISSUE THREAD

**Issue by blokhin** [Materials-Consortia/OPTiMaDe#249]
Dear colleagues,

unfortunately, almost no [up-to-date](https://www.optimade.org/providers/links) Optimade implementations currently serve [CORS header](https://github.com/Materials-Consortia/OPTiMaDe/blob/develop/optimade.rst#http-response-headers), which is in principle understandable, so I was a little bit naïve [suggesting that into a spec](https://github.com/Materials-Consortia/OPTiMaDe/pull/105).

**But a purely client-side Optimade Sky-Scanner app remains technically impossible.**

To workaround that and to encourage JS-only ecosystem in our field, a public HTTPS-ready server proxy (_e.g._ [this one](https://github.com/Rob--W/cors-anywhere)) is needed, obviously with the white-listed Optimade providers to prevent misuse.

I noticed you're already using [a server infrastructure](https://optimade.herokuapp.com), could we accommodate a CORS-bypassing server with the SSL cert there as well?

**Comment by rartino** [comment]
So, if I get this right, you want OPTiMaDe to host a service that proxies OPTiMaDe requests to a pre-defined set of databases to add CORS headers? That is an interesting idea. But won't this lead to huge data usage for that service, i.e., that everyone's gigantic data requests are being proxied?

**Comment by blokhin** [comment]
Exactly. But why do you think the data usage will be huge? We are speaking about rather limited audience and the textual content, which is nicely compressed by the modern servers out of the box. 

Today there are terabytes of free traffic included at a typical VPS per month. Let's say a normal single session consumes 1Mb of compressed traffic, so you'll be perfectly fine until an order of 1M sessions per month.

**Comment by rartino** [comment]
> But why do you think the data usage will be huge? We are talking about rather limited audience and the textual content, which is nicely compressed by the modern servers out of the box.

If I fully understand the technical solution, all web-based usage of OPTiMaDe would have the responses sent to this process from the real database and then out again to the web-based client. This consumes the bandwidth of the full response  for any query done. Especially for an in-browser "sky-scanner" implementation, this may send out the query to >20 databases and gather the responses, meaning 40 × typical response bandwidth usage for a single query. I can also bet on that a few misguided users will run scripts against this setup instead of directly against the databases.

If one instead implements the "sky-scanner" functionality in this process rather than completely in-browser, that would somewhat reduce the bandwidth usage.

That said, I'm not strongly opposed to a CORS proxy for OPTiMaDe. But whatever solution it uses for hosting should be kept very separate from our other services, so that the effect is limited when it runs out of bandwith.

A parallel idea that may help to better promote implementations to adopt CORS headers: how about adding a "cors_open" field to the providers database? This gives a bit of "advertising" for databases that are open to web client use in that those are the ones with that field set to `True`.

**Comment by blokhin** [comment]
>this may send out the query to >20 databases and gather the responses, meaning 40 × typical response bandwidth usage for a single query.

That’s okay. Or don’t you agree with my estimate on the traffic?

>misguided users will run scripts against this setup instead of directly against the databases

That’s not possible, unless you explicitly understand what you’re doing. You need to masquerade a web-browser.

>one instead implements the "sky-scanner" functionality in this process rather than completely in-browser

The UI should be anyhow in the web-browser, right? And as we find ourselves in such a cool environment, we certainly question if an intermediate server is needed (in an ideal world).

> `cors_open` field

Well, there’s such field already. It’s called `Access-Control-Allow-Origin`. Luckily, thanks to the solution I offer, there’s no need to set it up.

**Comment by blokhin** [comment]
@rartino closing as completed. Please, feel free to re-open if in doubt.

**Comment by rartino** [comment]
The existence of https://cors.optimade.org should probably be documented somewhere. Our readme?

**Comment by gmrigna** [comment]
@ml-evs If I remember correctly, you first made a request at GitHub and then I sent a message to the UClouvain sysadmins. Can we proceed in the same way?

**Comment by rartino** [comment]
Right, from your dig output, the uclovain nameserver was at some point configured to CNAME cors.optimade.org to alias.zeit.co., presumably resolving to an account set up by @blokhin . The question, I guess, is the cors server still there? Is it a service we should keep providing?

**Comment by ml-evs** [comment]
I don't think the CORS server is trying to run there, I believe the service running from @blokhin's domain at https://cors.optimade.science is still used, so presumably at some point the Vercel thing was moved to that and the original domain was left verified somehow?

So hopefully @gmrigna its a case of asking UCL to remove the cors.optimade.org CNAME record which is currently pointing at alias.zeit.co

**Comment by gmrigna** [comment]
I have now asked... Let us see what they respond.
