### ISSUE TITLE
Clarify when `lattice_vectors` MAY be `null` and how

### ISSUE THREAD

**Issue by CasperWA** [Materials-Consortia/OPTIMADE#253]
During the creation of a model validator for the Python tools (Materials-Consortia/optimade-python-tools#171) we find that the current description of `lattice_vectors` and how it MAY contain `null` vectors are a bit ambiguous.

It states that:

>- This property MUST be an array of dimensions 3 times 3 regardless of the elements of `dimension_types`. The vectors SHOULD by convention be chosen so the determinant of the `lattice_vectors` matrix is different from zero. The vectors in the non-periodic directions have no significance beyond fulfilling these requirements.
>- All three elements of the inner lists of floats MAY be `null` for non-periodic dimensions, i.e., those dimensions for which `dimension_types` is `0`.

Does this mean a vector within `lattice_vectors` MUST be either all `null` values or all number values?
And for calculating the determinant, one must then use `0` for `null` or?

Tagging the contributors to the references PR, @shyamd @ml-evs

**Comment by merkys** [comment]
The description does not place any strict requirements on the values of an unused dimension. They may be `null`, as well they may attain any numeric values.

**Comment by rartino** [comment]
My personal interpretation of the exact text gives that:
> Does this mean a vector within lattice_vectors MUST be either all null values or all number values?

Yes, I read it as a MUST-level requirement. (The type specification is "list of list of floats", i.e., the second level are floats. The final point allows for an exception to this, but only when "All three elements ...")

> And for calculating the determinant, one must then use 0 for null or?

The determinant isn't defined for a matrix with nulls; so it is automatically "different from zero". If one tries to follow the *spirit* of the specification, one may read it as a recommendation for all non-null vectors to be linearly independent (and we could clarify that.) But it isn't a huge issue since this is only a SHOULD-level requirement anyway.

**Comment by CasperWA** [comment]
> My personal interpretation of the exact text gives that:
> 
> > Does this mean a vector within lattice_vectors MUST be either all null values or all number values?
> 
> Yes, I read it as a MUST-level requirement. (The type specification is "list of list of floats", i.e., the second level are floats. The final point allows for an exception to this, but only when "All three elements ...")

The critical point is this question was `all`, i.e., MUST _all_ values in a vector be `null` if anyone of them are `null`?

**Comment by rartino** [comment]
@CasperWA 
> The critical point is this question was all, i.e., MUST all values in a vector be null if anyone of them are null? 

Yes, that was what I was trying to say. But you are correct this is ambiguous, the text is essential: "All three elements are floats, except all three elements MAY be null", and the second part can be interpreted both ways.

I assume we meant that either none or all of them are null (right?). So we need a fix for this.
