### ISSUE TITLE
Definition of an unknown position

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTIMADE#260]
Currently, structure feature `unknown_positions` is defined as the following:

> `unknown_positions`: This flag MUST be present if at least one component of the `cartesian_site_positions` list of lists has value `null`.

Taking crystallographic structure descriptions in CIF format into consideration, this seemingly means "*explicit* sites with unknown coordinates". However, there might be *implicit* sites such as:

* Attached hydrogens. Sometimes hydrogen coordinates are left undefined. Instead, their number is listed as a property of the atom they are bound to.
* Solvent molecules. These are usually left out, and this fact is not necessary documented.
* Other non-modeled sites. Existence of them in a crystal could be inferred from mismatch of the given and the calculated formulae (not as a rule, though).

How should we deal with these implicit sites? Are they important enough to be listed in `species_at_sites`, and, in turn, affect the `unknown_positions`?

**Comment by rartino** [comment]
I suppose we could greatly expand the specification text on how to handle these systems. However, it is clear to me that the only feature we support for this is via `null` in `cartesian_site_positions`.

Hence, my, possibly naïve, view of how these possibilities for unknown coordinates would be represented in the present OPTiMaDe specification is that you have to add ALL atoms that conceivably can be said to be "in the structure" to `species`, `species_at_sites` and correspondingly pad out your `cartesian_site_positions`. If you know where the atoms are, you specify the coordinates. If you don't know where they are, you set the coordinates to `null`.

So:
- Attached hydrogens: you make sure you have hydrogen in `species`, and you add extra hydrogens to `species_at_sites` and `cartesian_site_positions`. There presently is no way in OPTiMaDe to indicate that they are bound to a specific atom without specifying the coordinates, so you just set the coordinates for these hydrogens to be `null, null, null`. (You *could* e.g., add an `_exmpl_bound_to_site` member to the species definition inside `species` to retain the information about which site they are bound to. Perhaps we want to standardize this in a future version.)
- Solvent molecules: are they regarded as part of the structure and included in the formula or not? If yes, then you add them to `species_at_sites` and `cartesian_site_positions`, if no, then you leave them out and what we refer to as "the structure" contains no unknown positions.
- Other non-modeled sites: as far as I see we don't really allow a mismatch between a given and calculated formulae. So, add atoms to `sites`, `species_at_sites` and `cartesian_site_positions` with coordinates `null, null, null` until the given formula holds.

But this is coming from someone who more or less never have done anything useful with structures with unknown positions. So, if the above doesn't work, I guess there is no other option but to exclude these structures from OPTiMaDe access until the features that allow such systems to be described have been added in a future OPTiMaDe version.

As I recall, the discussion around issue #50 and #93 did call for input from anyone who works with these structures to add their input on what needs to be described.

**Comment by merkys** [comment]
I completely agree with you about adding the implicit sites to `cartesian_site_positions` with `null` coordinates.

However, implicit sites are seldom explicitly described in CIFs. (For example, [COD entry 2006714](http://www.crystallography.net/cod/2006714.html) contains 4 implicit water molecules, and this is evident only from formulae mismatch). In some cases only the mismatch of given and calculated formulae will signal about the implicit sites. Also the mismatch might be due to typographical mistakes and so on, so this method should not be trusted ultimately.

> As I recall, the discussion around issue #50 and #93 did call for input from anyone who works with these structures to add their input on what needs to be described.

Yes, I remember these discussions. It's possible that the issue of implicit sites did not occur to me then.

**Comment by rartino** [comment]
On a general level, in the difficult case you talk about you are dealing with an ambiguity in your source data (typo error or implicit sites), and you are essentially saying "I cannot carry this ambiguity over to the OPTiMaDe representation." 

And IMO it is a good thing that you cannot. 

There are two ways we could handle this situation: 
1. We extend OPTiMaDe to allow you to represent the ambiguity on a per-structure basis.
2. We only allow non-ambiguous data to be represented in OPTiMaDe, meaning database providers are forced to make the decision on how to resolve ambiguities, rather than pushing this difficulty onto users. 

I am very much in favor of '2' over '1', since I don't think a good format should allow ambiguity. An option for a provider with ambiguous data is to still serve it in an alternative database where one on *database-level* (rather than *structure-level*) indicates that these are structures the provider are unsure about.

Hence, specifically for the CIF case, I'd suggest:
- If you are very sure what is going on based on formula mismatch, then you modify `sites`, `species_at_sites`, `cartesian_site_positions` so that they are accounted for. Perhaps with a note added in, e.g., an `_exmpl_notes` field that this was done.
- If there is a formula mismatch but which cannot clearly be interpreted, then I would make the decision if the data I am serving is supposed to be a "high reliability" production database, in which case I would reject these structures. If not, I would include them with my best guess resolution of the ambiguity. (But then it would be a bug in my database if that resolution was done incorrectly.)

**Comment by merkys** [comment]
I am also in favor of option 2. Pinging @sauliusg as here we're close to dealing with policy decisions of the COD.

**Comment by sauliusg** [comment]
Hi, thanks for pinging.

I think data interpretation depends very much on application, and since database does not know what is the intended application it should not (and actually can not) interpret the data, but rather should represent faithfully what is known about the structure.

I agree, regarding option 1, that we can not represent all ambiguities that may be present in experimental structures, and we should not do this (otherwise Optimade JSON will duplicate the CIF framework, and there is not point doing that).

I would be in favour of modified option 2, in the following sense:

1. we drop the strict requirement that calculated summary (Hill) formula matches the one provided by the database;
2. we drop the requirement that *all* unknown atoms are present in the sites list; thus, atom sites 
3. we specify in the 'unknown_positions: "yes"' data item that the atom list is not complete.

Regarding 1: it makes little sense to require that both declared summary formula and formula calculated from coordinates match – client can easily calculated formula itself, and the declared formula becomes superfluous and confusing (broken SPOT; denormalised data). I would instead use the difference to indicate how many atoms are actually missing from the coordinate list;

Regarding 2: if the atoms with unknown coordinates can be inferred from the summary formula and/or species list, why should we bother and waste the bandwidth sending 'null' coordinates? The 'null' coordinates (later converted to NaNs) have sense if we know one atomic coordinate (say x=0 since an atom is on a special position) but not the others;

Regarding 3: this is a sole bit that allows to include/exclude structures with unknown coordinates in searches, and an indicator that some atomic coordinates are really missing. No need to send or check 'null' coordinates in the coordinate list; the flag would be sufficient.

This method would allow to represent all ambiguities present in experimental structures without over-interpreting the data. Some information would be lost, but the flag 'unknown_positions: "yes"' gives a clear indication that unknown atomic features are present, and the client can then get the full CIF with complete description if needed.

Does that seem like an acceptable compromise?

**Comment by rartino** [comment]
@sauliusg your proposal overall looks fine, however:
1. I'm fine with Hill formula not matching the calculated one. But I'd rather not have to textually parse the Hill formula field to deduce the amount and types of atoms left out of `species`, `species_at_sites`, and `cartesian_site_positions`. Aside being inconvenient, it also seems that parsing would easily be ambiguous, and we should try to avoid built-in ambiguities in the OPTiMaDe representation. So, in my opinion, this requires one additional field that somehow makes precise the species and counts of unknown atoms. 
2. This proposal interferes with my last proposed solution of #258. If we want to adopt that solution to allow for the case where a database cannot easily query for `unknown_positions` being present or not (which apparently is the case for COD), we may want to make sure the presence of `unknown_positions` affects structure data "inline", i.e., so that it is very difficult to "misinterpret" a response for an incorrect structure (e.g., leaving out all atoms at unknown positions.) 

Also, are we trying to push this for v1.0? Or can we keep the bandwidth-wasting nulls we have right now for v1.0?

**Comment by sauliusg** [comment]
>  1. I'm fine with Hill formula not matching the calculated one. But I'd rather not have to textually parse the Hill formula field to deduce the amount and types of atoms left out of `species`, `species_at_sites`, and `cartesian_site_positions`. Aside being inconvenient, it also seems that parsing would easily be ambiguous, and we should try to avoid built-in ambiguities in the OPTiMaDe representation. So, in my opinion, this requires one additional field that somehow makes precise the species and counts of unknown atoms.

I perfectly agree with your suggestion No. 1. Although parsing the Hill formula is not a big deal, having the summary formula encoded in JSON saves us specification of the Hill formula grammar, extra parser and removes the question of the element order.

Just – do we want it for 1.0? I would see this as a further development, thus appropriate for v1.1. We can probably live with Hill formulae for now.

**Comment by rartino** [comment]
But is parsing the Hill formula guaranteed to always yield an unambiguous fixed set of missing atoms? Right now the v1 specification has an unambiguous representation of unknown atoms: include them like any other atoms and set their coordinates to `null, null, null`. It seems to me it is better to keep that unambiguous representation and do the whole change (including the extra field) in the next version?

**Comment by sauliusg** [comment]
> 2\. This proposal interferes with my last proposed solution of #258. If we want to adopt that solution to allow for the case where a database cannot easily query for `unknown_positions` being present or not (which apparently is the case for COD), we may want to make sure the presence of `unknown_positions` affects structure data "inline", i.e., so that it is very difficult to "misinterpret" a response for an incorrect structure (e.g., leaving out all atoms at unknown positions.)

The difficulties of querying `unknown_positions` are implementation problems; though unpleasant, they are not so much an issue.

But when you duplicate information in several fields (flags and coords), then how do you know which is correct? You will say that specification says "they MUST match", but then what is the point of repeating the same information? And if you say that sloppy clients will not check the missing atom coordinates, by the same token they can forget to check formula-coordinate discrepancies.

**Comment by sauliusg** [comment]
> But is parsing the Hill formula guaranteed to always yield an unambiguous fixed set of missing atoms?

It should. We parse _chemical_formula_sum values for the COD, in most cases they match with what was calculated from the atomic coordinates and in the case they differ, this is a good indication of some peculiarity in the structure (not necessary error or problem ;).

**Comment by sauliusg** [comment]
> Right now the v1 specification has an unambiguous representation of unknown atoms: include them like any other atoms and set their coordinates to `null, null, null`.

This is indeed a good representation of atoms with unknown coordinates; however requiring that the *server* does extra analysis and inserts these `null` atoms whenever the formula is not matching the atom count  in the coordinate list sounds to me as asking too much from a database.

A database, IMHO, is supposed to retrieve and return information that is stored, and only do minimal required transformations (such as extracting info from SQL or CIF and converting to JSON or XML).

**Comment by merkys** [comment]
@rartino:
> But is parsing the Hill formula guaranteed to always yield an unambiguous fixed set of missing atoms?

It depends on whether the authors of a CIF file have included missing atoms in the formula or not. I am interested in doing a more throughout analysis of the COD: currently 80% entries have matching author-declared and computed formulae. That 20% is interesting to look into, plus there are more indications of missing atoms (such as [F000](https://www.iucr.org/__data/iucr/cifdic_html/1/cif_core.dic/Iexptl_crystal_F_000.html)) that we have been ignoring up to now.

> Also, are we trying to push this for v1.0? Or can we keep the bandwidth-wasting nulls we have right now for v1.0?

The decision regarding the missing atoms could be delayed for v1.1 or later, indeed.

**Comment by rartino** [comment]
> requiring that the server does extra analysis and inserts these null atoms whenever the formula is not matching the atom count in the coordinate list sounds to me as asking too much from a database. A database, IMHO, is supposed to retrieve and return information that is stored, and only do minimal required transformations (such as extracting info from SQL or CIF and converting to JSON or XML).

The desire to avoid such "heavy" transformations is already broken by OPTiMaDe asking you to serve the filled "P1" structure rather than just the representative atoms. Databases that store only the representative atoms (like COD does in CIFs) are already asked to do the transform to fill the cell before serving the data, and that is far heavier than adding the `null`s for atoms with unknown positions. 

It has been a goal (of mine, at least) that no implementation should be forced to alter or extend the data stored in their backend database to be able to serve OPTiMaDe. But, I don't think the goal you are trying to set now: that no implementation should have to do any major transform of their data before serving it, is a realistic goal for a common API. With that criteria, there would be very little commonality between the data received from different actors, and OPTiMaDe wouldn't be very useful compared to separate APIs.

**Comment by sauliusg** [comment]
> It has been a goal (of mine, at least) that no implementation should be forced to alter or extend the data stored in their backend database to be able to serve OPTiMaDe. But, I don't think the goal you are trying to set now: that no implementation should have to do any major transform of their data before serving it, is a realistic goal for a common API.

Sounds like an internal contradiction to me...

**Comment by rartino** [comment]
> Sounds like an internal contradiction to me...

No? 

Statement 1 is: No need to change of data stored in backend database. (So, mandatory queries should be translatable to queries against the underlying database engine.)

Statement 2 is: No need for API to invoke major transformation of data before sending it in a response.

I'm saying: 1 is a goal, 2 is not. That is not a contradiction.
