### ISSUE TITLE
Filtering on 'dimension_types'; suggestion for new 'periodic_dimensionality' field

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#275]
The discussion in #243 has opened up a more specific issue about the current definition of `dimension_types`.

As it stands, it is very difficult to query for 1D or 2D structures specifically, without checking for equality with all the possible orderings of `dimension_types` (e.g. `[1, 0, 0] OR [0, 1, 0] OR [0, 0, 1]` for 1D). This could be fixed by the suggestions in #243 for more direct filtering on lists, though it is not clear whether this solution will be ready for 1.0.

The suggestion is to create an auxiliary field, say `periodic_dimensionality` (name suggested by @rartino), that simply holds the sum of the current dimension types field for more useable querying. This will become especially useful when aggregating results between multiple databases, some of which may be focused entirely on low-dimensionality systems.

Some other suggestions for names (from discussions with @CasperWA  and @muhrin):
- `periodic_dimensionality` (@rartino's initial suggestion)
- `dimensionality` (so that it is next to `dimension_types` in the alphabetized response...)
- `ndimensions` (to follow the example of `nsites` and `nelements`)
- `periodicity`

This is obviously quite an easy field to add to the specification (pending the name), but there may be objections from providers about putting this field in before the 1.0 release, so please voice your concerns!

**Comment by mkhorton** [comment]
I like the simplicity of `sum(dimension_types)` by default. There are also good examples in the literature of continuous dimensionality measures given the ambiguity sometimes in assigning specific dimensionality (e.g. see doi 10.1103/PhysRevMaterials.3.034003). I could imagine some databases might want to query on this field, which practically would mean allowing for a floating point `dimensionality` in the spec.

**Comment by muhrin** [comment]
Just a quick question that related to @mkhorton 's point.  Does `dimension_types` only refer to the periodicity of the unit cell or some judgement on the periodicity of the thing contained within it.  For example, a cluster (which would be 0D) could still be in a fully periodic unit cell and, therefore, would have a `periodic_dimensionality` or 3.  You can think of any example you like for this (nano ribbons, molecular crystals, etc).

**Comment by mkhorton** [comment]
My view on this is that one is a periodicity imposed on the system, and the other is a property of the system. In this sense, perhaps a floating-point dimensionality is better included under a property API rather than the core API. My intention in raising this though is that if it _is_ part of the core API, it might be important to say that it may be floating point, and it is up to the individual database how they determine periodicity.

**Comment by ml-evs** [comment]
> Does `dimension_types` only refer to the periodicity of the unit cell or some judgement on the periodicity of the thing contained within it.

As far as I understand it, to the letter of the specification, there is nothing stopping an implementation from providing a fully-periodic unit cell for a low-dimensional structure. `dimension_types` allows you to specify that some of the lattice vectors can/should be ignored. 

I would argue that the spirit of the specification is to also use this field to provide the judgement on the dimensionality of the structure contained within the cell, as there is currently nowhere else to do so...

> My view on this is that one is a periodicity imposed on the system, and the other is a property of the system. In this sense, perhaps a floating-point dimensionality is better included under a property API rather than the core API.

I think I agree, and the specification for this new field should be clear to state that this is the imposed periodicity (I think the chosen field name should clearly reflect that too).

**Comment by giovannipizzi** [comment]
Just a historical perspective on the choice of the name `dimension_types` in this [comment](https://github.com/Materials-Consortia/OPTIMADE/issues/23#issuecomment-397362377) (I feel old now ;-) ). 

And indeed, I think the original discussion was that it's up to the DB to decide if they want to represent a structure (say a molecule) in PBC or not (in the end they are two different structures anyway)

**Comment by rartino** [comment]
I find the suggestions along the line of `dimensionality` problematic, because everything we represent is still 3-dimensional, what is being specified by this parameter is the periodicity. (E.g., I'm not comfortable with saying that a molecule is "0-dimensional".)

**Comment by muhrin** [comment]
I'm updating this issue with discussions held in the zoom chat this morning.

It was generally agreed that _if_ a new field is included, it should be simply the sum of `dimension_types` rather than any more sophisticated determination of the dimensionality of the contents of the unit cell.  The rationale behind this is that a server that provides `dimention_types` (which is currently required) can add this easily while adding a field that is less clearly defined would be more difficult to agree upon in time for v1.0.  It was judged that this can wait until after this point.

As for names, a series of votes were held culminating in the following.

A.`nperiodic_dimensions`
B. `nperiodic`
C. `ndimensions`
D. `periodic_dimensionality`
E. `periodic_dimensions`

Markus Scheidgen : A
Saulius Gražulis : B,A
Giovanni Pizzi : A,B
Martin Uhrin : E, A
Casper Welzel Andersen : A,C
Rickard Armiento : Vote: A, D
fekad : A C

It was agreed that `nperiodic_dimensions` gathered the broadest overall support.

The discussion can continue in this issues, particularly if there are any disagreements or comments on the above.

**Comment by ml-evs** [comment]
Sorry for missing the discussion on this, but I also strongly support `nperiodic_dimensions`.

**Comment by rartino** [comment]
The fix for this was merged in #278, right? So this can be closed? @ml-evs, if you agree, please close.

**Comment by ml-evs** [comment]
Yep, closed by #278!
