### ISSUE TITLE
Remove requirements on index_base_url in meta, or remote it completely?

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTIMADE#297]
As I was working on the specification, I came across the `index_base_url` field inside the top-level `meta`:
>  If the index meta-database (see section `Index Meta-Database`_) is implemented by the provider, the :field:`index_base_url` field MUST be included.

I read this to say that if there exists an index meta-database for a provider, and the response includes a top-level meta (which, strictly speaking, is optional on the SHOULD level, but one nearly always want to do), then that index meta-database MUST be linked here.

This seems problematic now that we, for some providers, handle their index meta-databases for them in the providers repository. It seems we are saying that, e.g., `cod` and `tcod` MUST link back to the index meta-db in the providers repository in the meta field of *every response* they provide.

I don't see why we should have this requirement at all.

Even further, why is this redundant `index_base_url` in the meta at all? We implemented `root`-type links in the `/links` endpoint that seem to cover this perfectly. Shouldn't we altogether remove the `index_base_url` field from the meta tag?

**Comment by CasperWA** [comment]
Sure. The _new_ `root`-type links can take care of this now. However, note that the `/links` endpoint is not MANDATORY (as far as I remember), hence there is a risk that one may "traverse a tree of databases" and end up on a "leaf" without knowing how to get back to the start. Although I will say that if a provider has a "tree" of databases, they probably also implement the `/links` endpoint in order to show the tree... So maybe it is an edge case that will/should never exist?

**Comment by rartino** [comment]
> note that the /links endpoint is not MANDATORY (as far as I remember)

Isn't it? At https://github.com/Materials-Consortia/OPTIMADE/blame/develop/optimade.rst#L1183 :
> The links endpoint MUST be provided under the versioned base URL at /links.

*(However, I note now that this "versioned base URL" needs an edit due to #290, and I see the same thing in a few other places as well ...)*

> So maybe it is an edge case that will/should never exist?

I'm not sure what the use case is where things break badly due to a client not finding the root of a provider that, for some reason, has decided not to provide that link.

**Comment by CasperWA** [comment]
> > note that the /links endpoint is not MANDATORY (as far as I remember)
> 
> Isn't it? At https://github.com/Materials-Consortia/OPTIMADE/blame/develop/optimade.rst#L1183 :
> 
> > The links endpoint MUST be provided under the versioned base URL at /links.

I remembered badly. Thanks!

> > So maybe it is an edge case that will/should never exist?
> 
> I'm not sure what the use case is where things break badly due to a client not finding the root of a provider that, for some reason, has decided not to provide that link.

I never said or thought that a client would break badly due to not being able to find the `root` from _any_ response. I was merely trying to think up an edge-case where the `index_base_url` may be a useful resource to have.
However, since the `/links` endpoint _is_ REQUIRED/MANDATORY, then there is no edge-case for me to think up that will in any way break a client, badly or just mildly.
