### ISSUE TITLE
elements="Si,O2" in filter language examples

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTIMADE#355]
There are examples in the specification having filter values containing `elements="Si,O2"` (legal filter language expression). As `elements` is a list property and per "Type handling and conversions in comparisons" cannot be compared to string values (MUST be reported as HTTP 501), I suggest replacing `elements="Si,O2"` with something that would normally be supported by providers, for example, `chemical_formula_reduced="ClNa"`.

**Comment by CasperWA** [comment]
I was of the impression `elements="Si,O2"` is not legal, but rather `elements="Si","O"`, since elements needs to be a list containing strings of elements, i.e., not labels for sites or similar?

**Comment by merkys** [comment]
`elements="Si,O2"` is a legal filter language expression. However, comparing list properties to strings MUST NOT be supported.

`elements="Si","O"` is illegal filter language expression. `elements HAS ALL "Si","O"` is legal filter language expression, and MUST be supported as per specification.

**Comment by CasperWA** [comment]
Reading [`elements`](https://github.com/Materials-Consortia/OPTIMADE/blob/develop/optimade.rst#elements), it seems to me it should be a list that doesn't contain site labels (like `O2`), but only chemical elements.
So that part of the example is definitely wrong (as I interpret it).

Since string values have to be enclosed in double quotations, and `Si,O` is not a string value, but a representation of string values in a list, I don't know that `elements="Si,O"` makes sense?
I'm finding it hard to decipher from the filter language section whether lists _must_ also support conventional operators or not, like `=`. I must admit that my impression was not - and that the `HAS` was meant to compensate for this since ambiguity could arise?

Even if `=` is allowed, it would be similar to something like `HAS EXACTLY` or something? Where the individual members would still be strings, i.e., encompassed in double quotations, and then separated by commas.

So I guess the conclusion from my side is that we need to be specific about lists in the filter language section - or more specifically, for which property types conventional operators can be used?

**Comment by rartino** [comment]
My understanding is that the only tests one can do for lists are the HAS-type operators and LENGTH to test list lengths. Way back HAS EXACTLY (or similarly named) was on the table, but it was taken out in an edit by me because I couldn't figure out how to unambiguously define its behavior when duplicated elements could be present (an issue that was further exacerbated if one allows operators like > in line with how our other HAS-type operators work.)

Arguably `elements="Si","O"` for a simple *ordered* (right?) list equality test makes sense, though.

**Comment by merkys** [comment]
> Reading [`elements`](https://github.com/Materials-Consortia/OPTIMADE/blob/develop/optimade.rst#elements), it seems to me it should be a list that doesn't contain site labels (like `O2`), but only chemical elements.

Right, there should only be element names, without counts.

> Since string values have to be enclosed in double quotations, and `Si,O` is not a string value, but a representation of string values in a list, I don't know that `elements="Si,O"` makes sense (which might also be your point ;) )?

["Type handling and conversions in comparisons"](https://github.com/Materials-Consortia/OPTIMADE/blob/develop/optimade.rst#id52) forbids (MUST) comparing list properties to strings.

> I'm finding it hard to decipher from the filter language section whether lists _must_ also support conventional operators or not, like `=`. I must admit that my impression was not - and that the `HAS` was meant to compensate for this since ambiguity could arise?

Per specification `=` have to be followed by simple (non-list) constant or another identifier (optionally supported feature). Thus there is no syntactic support for comparing list property to a list via `=`.

> Even if `=` is allowed, it would be similar to something like `HAS EXACTLY` or something? Where the individual members would still be strings, i.e., encompassed in double quotations, and then separated by commas.
> 
> So I guess the conclusion from my side is that we need to be specific about lists in the filter language section - or more specifically, for which property types conventional operators can be used?

To me the specification is quite clear, but examples are confusing.

**Comment by merkys** [comment]
> Arguably `elements="Si","O"` for a simple _ordered_ (right?) list equality test makes sense, though.

Agree. This would indeed simplify such queries on element lists.

**Comment by CasperWA** [comment]
Right. So this issue represents that the examples should be changed? I think we have other issues for suggesting using operators on lists (or at least the equality operator). At least there should be some based on the previous discussion of `HAS EXACTLY` and such?

**Comment by merkys** [comment]
> Right. So this issue represents that the examples should be changed? I think we have other issues for suggesting using operators on lists (or at least the equality operator). At least there should be some based on the previous discussion of `HAS EXACTLY` and such?

#243 discusses comparisons with lists, but the thread has been quiet there since the last workshop. Until that one turns into a PR, we could fix the examples.

> Edit: Which is also what you write in the OP. And sure - just make a PR :) It might be good to go through all examples like this to ensure consistency with the newest property/field definitions.

Good idea :) Will do that.
