### ISSUE TITLE
The next OPTIMADE release: v1.0.1 or v1.1.0?

### ISSUE THREAD

**Issue by ml-evs** [Materials-Consortia/OPTIMADE#366]
At the workshop, we discussed the best way to approach our imminent next release, given that some amount of cherry-picking/history rewriting was required. I believe we now have two options that maintain a linear history, with references back to original PRs and parent commits.

This continues some of the discussion from #340, and I'll tag a few people here who were part of the previous discussion on here and at the workshop.

@rartino @merkys @shyamd @sauliusg @CasperWA @giovannipizzi 

1. :tada:  Merge #365 (after bumping version numbers), which includes the `issue_tracker` addition and all other changes, and release it as v1.1.0.
2. :rocket:  Merge #351, which includes commits that *revert* the issue tracker changes, release v1.0.1, and then immediately reintroduce the `issue_tracker`.

Feel free to vote-react with your preference, if you do not wish to comment explicitly...

For the future, there were two main suggestions:

1. Run a `v1.0.x` branch (which receives cherry-picked hot-fixes) alongside `develop` (which tracks all changes) and `master` (which contains the latest release).
2. Make an appropriate release per merged PR (@shyamd)

**Comment by merkys** [comment]
I guess for now it is easier to pool all post-v1.0.0 changes together and release them as v1.1.0. I cannot remember anything tying us to v1.0.x.

> For the future, there were two main suggestions:
> 
> 1. Run a `v1.0.x` branch (which receives cherry-picked hot-fixes) alongside `develop` (which tracks all changes) and `master` (which contains the latest release).

I would suggest alternative branch name `patches`, as `v1.0.x` will be obsolete soon, and having a persistent name for a branch is nice, as one can refer to that in the documentation of the release procedure, and I think this would be easier to understand for a newcomer.

> 2. Make an appropriate release per merged PR (@shyamd)

This could be done. However, I would prefer shorter intervals between patch releases, and I believe many people would not be happy about too frequent minor releases.

**Comment by ml-evs** [comment]
I am also leaning towards 1.1, for the sake of simplicity, and for ease of validating implementations. In future we should be very strict that patch versions only clarify/fix descriptions of fields, rather than changing any representations (as with species.mass) and any new fields (as with issue tracker). Of course, there is nothing stopping us from backporting typo fixes etc. to a v1.0.1 release, should we want to...

It would be good to decide on this and release so we can update links in the proofs of the paper. Any objections from the others in the previous discussion? @rartino @shyamd @sauliusg @CasperWA @giovannipizzi

**Comment by shyamd** [comment]
We added a new feature. The version bump should reflect this. I vote `v1.1.0`  and not tying our hands maintaining a "v1.0.x" branch. This is a specification, not a program. Just because we port changes to the `v1.0.x` branch and add "fixes" doesn't mean anyone implementing optimade will make those changes. Why wouldn't they just update to the latest spec, since that has those same "fixes" already?

**Comment by ml-evs** [comment]
If there are no further comments, I think we have waited long enough, and I will release v1.1 from the current state of the develop branch at the end of this week.

**Comment by rartino** [comment]
I'm contemplating @shyamd's point about the need for maintaining older branches.

How precisely do we interpret the semantic versioning requirement that `v1.x` -> `v1.y` where `y = x+1` must not break backwards compatibility?

1. I think we all agree that it means that we cannot add anything to the specification `v1.y` that breaks a *client* whose requests confirm to the `v1.x` specification.
2. But does it also mean that we cannot add anything to the specification `v1.y` that would make an implementation confirming to `v1.x` to not confirm to `v1.y`?

If point 2 is true, then @shyamd is correct in that there is no need to maintain older point releases, e.g., `v1.x`. Implementations should just clam to implement the latest `v1` specification to refer to a version of the specification with all relevant patches included.

However, this interpretation means that we will need a major version bump even for e.g., bumping a field from recommended to required. (Since a valid `v1.x` implementation that leaves that field out will not confirm to `v1.y`.) The problem I see is that this policy may lead to major-version-bumps at a lot of things that does not break clients. Hence, it will be a mess for clients to know which versions they are compatible with.

The alternative viewpoint is to specifically decide that the semantic version number refers to the view of clients. One may argue that in a more common situation with a single API implementation (rather than OPTIMADE's specification of an API), this is in fact how it works. The semantic version is for clients of the API to automatically determine when it can expect compatibility.

Another alternative would be to keep track separately of the specification version number and the OPTIMADE protocol version number.

**Comment by rartino** [comment]
Since we started to discuss that we may need a v1.0.1 for the sake of providing sensible schemas for v1.0 via Materials-Consortia/schemas#5, I have gone ahead and created a v1.0 branch in the main OPTIMADE repo. It tracks the same develop history as develop up until the point when the first new feature was merged (#339), at which point the develop branch implicitly starts tracking the to-be v1.1, and this branch tracks v1.0.

I get the concern about extra work in maintaining all old releases. But, we really don't need to maintain these branches until we see a need to make a patch release, at which point someone has to do exactly what I just did  - go through the graphical log of commits and merge/cherry-pick patch PRs into the branch.

**Comment by shyamd** [comment]
There are multiple ways to do this. Semver might not even be the most appropriate for protocols. Typically, the breaking changes are bundled together into a "dev" version or something until there is a critical mass of them, at which point a new major version is released.

**Comment by ml-evs** [comment]
Closing this, as we released v1.1 a while ago and will be releasing v1.0.1 imminently.
