### ISSUE TITLE
"4.1.1. URL Query Parameters" contains a reference to 'jsonapi' format

### ISSUE THREAD

**Issue by merkys** [Materials-Consortia/OPTiMaDe#4]
[4.1.1. URL Query Parameters](https://github.com/merkys/OPTiMaDe/blob/master/optimade.md#411-url-query-parameters) contains a reference to 'jsonapi', which has been renamed to 'json' recently. This should be removed, or am I missing something?

**Comment by merkys** [comment]
Fix pending in PR #5.

**Comment by rartino** [comment]
I'm not sure why you think 'jsonapi' was to be renamed to 'json'? I thought it made sense to keep the new name to avoid confusion with any lingering implementations of the pre-0.9.5 format. Is there a reason you feel strongly that the standard output format needs to be named 'json' rather than 'jsonapi'?

**Comment by merkys** [comment]
OK, it makes sense, although I don't think that lingering pre-release implementations would cause any problems. Nevertheless, I consider this closed and will undo my replacement in #5.
