### ISSUE TITLE
What to return for requests to the base_url

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#60]
As far as I see in the specification, we do not currently say what to return for a request to the base_url. Should we?

I'd propose something like this:
```
{
    "data": [
        {
            "id": "/",
            "type": "OPTIMaDe base url"
            "attributes": {
                "available_endpoints": [
                    [
                        "structures",
                        "calculations"
                    ]
                ]
            },
        }
    ]
}
```

But, then I realized; for #46 and PR #56 we are now discussing that an "index" meta-database should be possible to be hosted with just static files. When doing do, it may in some hosting situations be an obstacle to have to return something specific for a request for the "directory" where the files are stored. 

So, maybe we should say that this is optional? But when implementing it just seemed weird not to say *anything* about what the base URL returns.

**Comment by CasperWA** [comment]
Initially in my implementation, I set it to redirect to the given `info` endpoint.
But yes, let's ruminate a bit on it after the "index" meta-database has been finalized as an addition to the specification.

**Comment by rartino** [comment]
Having given this a bit of thought, in particular with regards to the hope to be able to host index points with static files, I think we should say that there is no requirement to return anything specific (even a 404 error is acceptable), but that we suggest that a html page is returned with human-readable content that communicates how data can be queried if an OPTIMaDe-aware client is pointed at this URL.

**Comment by ltalirz** [comment]
I ran into the same question, and I agree with @rartino that the response to this endpoint is probably mainly relevant for humans entering the URL in their browsers (software clients don't need it). Returning "not found" is obviously not very user friendly.

I've had a bit of a look around what others do:
* Wikipedia: https://en.wikipedia.org/w/api.php
* Open weather: http://api.openweathermap.org/data/2.5
* Youtube analytics: https://youtubeanalytics.googleapis.com/v2
* Fitbit: https://api.fitbit.com/1

It seems that people are surprisingly comfortable with returning errors at the base url - however, they tend to have great documentation elsewhere and you don't land on the API directly when you search for their API on Google.

Maybe this is actually the main take home message here?

What I would be looking for as an optimade user is essentially this:
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/Materials-Consortia/optimade-python-tools/master/openapi.json#/operation/get_structures_structures_get
and I would vote to include this as a top-level link "API documentation" optimade.org (it should actually be the first link, right after the "home" button. Perhaps the link to the Wiki can be sacrificed to make space).

@gmrigna Do you agree?

As for the original question: Since we are writing a JSON API here, returning an HTML page at the base url doesn't seem consistent to me. 
This leaves the JSON format, which isn't really that human readable, and if we want to stick with the same response format as for other endpoints, it gets quite messy. Perhaps the focus should really lie on directing humans to the documentation first.

That said, the spec should still make at least a recommendation on what to return at the base url  - or we all start doing different things, it will be a mess. 
My suggestion would be to simply return a 404 "not found".

**Comment by rartino** [comment]
To somewhat repeat my observation above, to enable all scenarios that have been discussed for hosting the index database, I don't think we can make a firm requirement here.

JSON API or not, I think a free-form web page would be the most helpful. In contrast to the other APIs you cite, we are going to throw around URLs to OPTiMaDe API implementations for a while as part of organizing interoperability. It will be very likely that users that don't know what OPTiMaDe is will visit these URLs in a browser.

To get around the JSON API argument, we can simply say ~  "The base URL isn't part of the protocol, and thus fully under the control of the API implementation. However, it is RECOMMENDED that the API implementation serves a html document here that explains that the URL leads to an OPTiMaDe endpoint that can be queried using an OPTiMaDe client."
