### ISSUE TITLE
Data response format when only one item can ever be returned

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/OPTiMaDe#61]
The jsonapi specification gives examples for when the "primary data is a single resource object:"  And in those cases the returned 'data' is not a list, but directly the dictionary for that single resource object. Here is an example directly from the jsonapi specification:
```
{
  "data": {
    "type": "articles",
    "id": "1",
    "attributes": {
      // ... this article's attributes
    },
    "relationships": {
      // ... this article's relationships
    }
  }
}
```

In the queries in OPTIMaDe that only ever will return a single item in data, maybe it would be cleaner to follow their example?

So for the info endpoint we now have this:
```
{
  ... <other response items> ...
  "data": [
    {
      "type": "info",
      "id": "/",
      "attributes": {
        "api_version": "v0.9",
        "available_api_versions": {
          "0.9.5": "http://db.example.com/optimade/v0.9/",
          "0.9.2": "http://db.example.com/optimade/v0.9.2/",
          "1.0.2": "http://db.example.com/optimade/v1.0/"
        },
        "formats": [
          "json",
          "xml"
        ],
        "entry_types_by_format": {
          "json": [
            "structure",
            "calculation"
          ],
          "xml": [
            "structure"
          ]
        },
        "available_endpoints": [
          "entry",
          "all",
          "info"
        ]
      }
    }
  ]
}
```
But maybe it should be this:
```
{
  ... <other response items> ...
  "data": {
      "type": "info",
      "id": "/",
      "attributes": {
        "api_version": "v0.9",
        "available_api_versions": {
          "0.9.5": "http://db.example.com/optimade/v0.9/",
          "0.9.2": "http://db.example.com/optimade/v0.9.2/",
          "1.0.2": "http://db.example.com/optimade/v1.0/"
        },
        "formats": [
          "json",
          "xml"
        ],
        "entry_types_by_format": {
          "json": [
            "structure",
            "calculation"
          ],
          "xml": [
            "structure"
          ]
        },
        "available_endpoints": [
          "entry",
          "all",
          "info"
        ]
      }
    }
}
```

Perhaps more important, this also seems to trigger an ambiguity in the present specification for what we call "Single entry endpoints", i.e. for this request:
 http://example.com/optimade/v0.9/structures/exmpl:struct/3232823
Should one return this:
```
{
  ... <other response items> ...
  "data": [
    {
      "type": "structure",
      "attributes": {
        "formula": "Es2"
        "local_id": "exmpl:struct/3232823",
        "url": "http://example.com/structures/exmpl:struct/3232823",
        "immutable_id": "http://example.db/structs/1234@123",
        "last_modified": "2007-04-07T12:02Z"
      },
    },
  ]
}
```
Or this:
```
{
  ... <other response items> ...
  "data": {
      "type": "structure",
      "attributes": {
        "formula": "Es2"
        "local_id": "exmpl:struct/3232823",
        "url": "http://example.com/structures/exmpl:struct/3232823",
        "immutable_id": "http://example.db/structs/1234@123",
        "last_modified": "2007-04-07T12:02Z"
      }
  }
}
```
And, regardless of what we decide, we probably should add an example response in that section of the specification.

**Comment by CasperWA** [comment]
I saw this in the JSON API specification as well. There are some other things as well (I will open issues for them later, depending on the result of this one).

If the rule is to keep the specs as close to the JSON API specs as possible, OPTiMaDe should reflect the choice of *not* returning an array/a list when the *expected* response is a single entry.

However, we may choose to "simplify" a bit the OPTiMaDe spec, by saying `data` MUST return an array/a list, no matter what is expected. If no data is returned, it should be an empty list.
This may make the client implementation easier in some ways, but will inevitably veer away from the object of having a JSON API v1.0 specification.

In my opinion, I think it may be easier to reimplement the decisions already taken in the JSON API specs, i.e. if the *expected* result is a single resource object, `data` MUST be `null` if no object is returned, and otherwise return the resource object directly.

**Comment by rartino** [comment]
Yes, my opinion is also to follow jsonapi in this, specifically for queries that can only result in 1 or 0 results.

**Comment by merkys** [comment]
> Yes, my opinion is also to follow jsonapi in this, specifically for queries that can only result in 1 or 0 results.

I second this opinion.
